package pathfinder;

public enum Descriptor {
	ACID, AIR, CHAOTIC, COLD, DARKNESS, DEATH, EARTH, ELECTRICITY, EVIL, FEAR, FIRE, FORCE, GOOD, LANGUAGE_DEPENDENT,
	LAWFUL, LIGHT, MIND_AFFECTING, SONIC, WATER;
}
